from enum import StrEnum


class OrderState(StrEnum):
    DISCOVERED = "DISCOVERED"
    CLAIMED_IMPORTED = "CLAIMED_IMPORTED"
    OPEN_FOR_ALLOCATION = "OPEN_FOR_ALLOCATION"
    ASSIGNMENT_PENDING_APPROVAL = "ASSIGNMENT_PENDING_APPROVAL"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESULT_SUBMITTED = "RESULT_SUBMITTED"
    QC_PENDING = "QC_PENDING"
    SUBMITTING_TO_SITE = "SUBMITTING_TO_SITE"
    DONE = "DONE"
    REASSIGNMENT_REQUIRED = "REASSIGNMENT_REQUIRED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"
    EXCEPTION = "EXCEPTION"
