"""order detail mirror fields

Revision ID: 4d849c8b19ce
Revises: 54d3d45e8eb9
Create Date: 2026-09-07 20:34:59.823669

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d849c8b19ce'
down_revision = '54d3d45e8eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_name', sa.String(length=512), nullable=True))
    op.add_column('orders', sa.Column('thumbnail_url', sa.String(length=1024), nullable=True))
    op.add_column('orders', sa.Column('sku', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('product_category', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('product_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('job_type', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('has_template', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('orders', sa.Column('multiple_design', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('orders', sa.Column('double_sided', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('orders', sa.Column('priority_label', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('created_at_ext', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('order_created_at_ext', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('deadline_at_ext', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('note_outsource', sa.Text(), nullable=False, server_default=sa.text("''")))
    op.add_column('orders', sa.Column('order_note', sa.Text(), nullable=False, server_default=sa.text("''")))
    op.add_column('orders', sa.Column('custom_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('design_tool_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'design_tool_url')
    op.drop_column('orders', 'custom_config')
    op.drop_column('orders', 'order_note')
    op.drop_column('orders', 'note_outsource')
    op.drop_column('orders', 'deadline_at_ext')
    op.drop_column('orders', 'order_created_at_ext')
    op.drop_column('orders', 'created_at_ext')
    op.drop_column('orders', 'priority_label')
    op.drop_column('orders', 'double_sided')
    op.drop_column('orders', 'multiple_design')
    op.drop_column('orders', 'has_template')
    op.drop_column('orders', 'job_type')
    op.drop_column('orders', 'product_variants')
    op.drop_column('orders', 'product_category')
    op.drop_column('orders', 'sku')
    op.drop_column('orders', 'thumbnail_url')
    op.drop_column('orders', 'product_name')
    # ### end Alembic commands ###
